### ISSUE TITLE
Intoruducing the infoblox project into http://projects.theforeman.org/projects for issue tracking?

### ISSUE THREAD

**Issue by iNecas** [theforeman/smart_proxy_dns_infoblox#5]
Hi,

We would like to work on getting the infoblox-related code in to more handes of our upstream users, we plan on working on packaging, installer support, documentation etc. Basically making this more official part of the Foreman ecosystem.

Since most of the plugins we have in the ecosystem use Redmine for tracking issues, both users and developers are used to have it, as well as we have the planning and release processes built on top of the tool, I would like to ask you, if you are ok with having an Infoblox sub-project open there to track the issues?

**Comment by sjoeboo** [comment]
@iNecas thats totally fine with me!

**Comment by domcleal** [comment]
I've created http://projects.theforeman.org/projects/infoblox for you with separate DNS/DHCP issue categories (hopefully that's the easiest way to do both) and git repo syncing/issue closing for both. @sjoeboo has permission to manage it.

I can disable issues on the GitHub repos too if you like, once the open tickets are closed.
